### ISSUE TITLE
'MultiDetector' object has no attribute 'detected_callback'

### ISSUE THREAD

**Issue by nsxr51** [nyumaya/nyumaya_audio_recognition#17]
**Describe the bug**
after detecting "word" with MultiDetector  
throw exception 

  Traceback (most recent call last):
    Traceback (most recent call last):
  File "multi_streaming_example.py", line 90, in <module>
    label_stream(FLAGS.libpath)
  File "multi_streaming_example.py", line 68, in label_stream
    threading.Thread(target=FTask(frame,extractor_gain)).start()
  File "multi_streaming_example.py", line 39, in FTask
    mDetector.run_frame(features)
  File "./src/multi_detector.py", line 134, in run_frame
    if(self.detected_callback):
AttributeError: 'MultiDetector' object has no attribute 'detected_callback'

**To Reproduce**
running multi_streaming_example.py 

**Platform**
aarch64

**Comment by yodakohl** [comment]
Thank you very much for the issue report. I fixed the issue with the latest commit.
